### ISSUE TITLE
DLL fails to locate resource with id 101

### ISSUE THREAD

**Issue by 5sigmapoint2** [overfl0/Pythia#3]
From Overflo:
I finally found the cause after running Arma and connecting with a debugger to the DLL: it throws an exception at ResourceLoader.cpp:18

`Unable to find resource with id 101 because of error with code 0`

**Comment by 5sigmapoint2** [comment]
`GetModuleHandle(NULL)` will return a handle of the calling process (.exe) 
`FindResource(NULL, ID, ID)` searches the module used to create the current process (.exe)

[FindResource](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648042%28v=vs.85%29.aspx)

**Comment by overfl0** [comment]
Seems to work now.
