### ISSUE TITLE
ResourceLoader::loadTextResource loads additional data

### ISSUE THREAD

**Issue by overfl0** [overfl0/Pythia#7]
I don't know what's happening but loadTextResource sometimes loads Adapter.py with some windows assembly data appended.

No idea why this is happening.

End of Adapter.py as loaded by the method. The comment is mine, all the "<?xml" isn't.
```
FUNCTION_CACHE = {
    'Pythia.ping': ping,
    'Pythia.test': test,
    'Pythia.continue': continue_coroutine,
    'Pythia.test_coroutines': test_coroutines,
}

# Somehow Visual Studio cannot load this if there is a newline at The
# end of the file<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<assembly xmlns='urn:schemas-microsoft-com:asm.v1' manifestVersion='1.0'>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level='asInvoker' uiAccess='false' />
      </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
```

**Comment by overfl0** [comment]
Hey! @5sigmapoint2 it's quite of a showstopper bug because it seems to be happening randomly and you never know when it's going to break after you make some changes to the python code.
Could you take a look at this in the near future?

The last time I had this was when I made some changes and AppVeyor generated a faulty dll, which means this was done on a clean environment in a clean VM. If there is no way to fix this maybe we should look for another (cross-platform this time) way to store python files?

To make an ad-hoc fix, you just have to add some data - some text, maybe comments - inside adapter.py and recompile.
This was tested by adding something at the end of the file. Maybe doing so in the middle changes this as well but I have not tested that.

**Comment by 5sigmapoint2** [comment]
Problem seems to be we can't assume the string will be zero-terminated, so we need to find out the size of the resource and build the string using that.
